### ISSUE TITLE
Training Reward Model: AttributeError: 'Namespace' object has no attribute 'residual_dropout_lima'. Did you mean: 'residual_dropout'?

### ISSUE THREAD

**Issue by RylanSchaeffer** [tlc4418/llm_optimization#5]
I'm trying to train a reward model using the given default configurations but I hit an odd error:

Command:

```
accelerate launch --config_file configs/accelerate_config.yaml src/reward_modeling/training/trainer_rm.py --configs defaults_rm rm-pythia-44m
```

Error:

```
Traceback (most recent call last):
  File "src/reward_modeling/training/trainer_rm.py", line 351, in <module>
    main()
  File "src/reward_modeling/training/trainer_rm.py", line 209, in main
    model = get_model(training_conf, tokenizer)
  File "miniconda3/envs/reward_modeling_env/lib/python3.10/site-packages/model_training/utils/utils.py", line 354, in get_model
    residual_dropout_lima=conf.residual_dropout_lima,
AttributeError: 'Namespace' object has no attribute 'residual_dropout_lima'. Did you mean: 'residual_dropout'?
```

**Comment by RylanSchaeffer** [comment]
It might be a bug with Open Assistant: https://github.com/LAION-AI/Open-Assistant/issues/3690

**Comment by RylanSchaeffer** [comment]
I found I needed to add `residual_dropout_lima: false` to `defaults_rm` inside `config_rm.yaml`

**Comment by sheikhshafayat** [comment]
Thanks your solution worked for me!
